export const FIREBASE_API_KEY =
  process.env.NEXT_PUBLIC_FIREBASE_API_KEY || 'APP_FIREBASE_API_KEY'

export const FIREBASE_APP_ID =
  process.env.NEXT_PUBLIC_FIREBASE_APP_ID || 'APP_FIREBASE_APP_ID'

export const FIREBASE_MEASUREMENT_ID =
  process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID ||
  'APP_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'

export const FIREBASE_MESSAGING_SENDER_ID =
  process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ||
  'APP_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'

export const FIREBASE_PROJECT_ID =
  process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ||
  'APP_NEXT_PUBLIC_FIREBASE_PROJECT_ID'
